### ISSUE TITLE
Can't find SO file

### ISSUE THREAD

**Issue by Gnome16** [eriklins/Pascal-Bindings-For-SimpleBLE-Library#12]
A problem with my Linux Mint 21 set up I'm sure, but there doesn't seem to be any way to contact Erik other than raising an issue. I'm getting SO errors:

```
graham@graham-dell:~/Pascal/SimpleBLE$ ls -la
total 5124
drwxrwxr-x 2 graham graham    4096 Jan 21 13:49 .
drwxrwxr-x 8 graham graham    4096 Jan 21 13:40 ..
lrwxrwxrwx 1 graham graham      11 Jan 21 13:49 libfmt.so -> libfmt.so.8
lrwxrwxrwx 1 graham graham      15 Jan 21 13:49 libfmt.so.8 -> libfmt.so.8.1.1
-rwxrwxr-x 1 graham graham  576824 Nov  7 02:14 libfmt.so.8.1.1
lrwxrwxrwx 1 graham graham      19 Jan 21 13:49 libsimpleble-c.so -> libsimpleble-c.so.0
lrwxrwxrwx 1 graham graham      23 Jan 21 13:49 libsimpleble-c.so.0 -> libsimpleble-c.so.0.6.0
-rwxrwxr-x 1 graham graham  205440 Nov  7 02:14 libsimpleble-c.so.0.6.0
lrwxrwxrwx 1 graham graham      17 Jan 21 13:49 libsimpleble.so -> libsimpleble.so.0
lrwxrwxrwx 1 graham graham      21 Jan 21 13:49 libsimpleble.so.0 -> libsimpleble.so.0.6.0
-rwxrwxr-x 1 graham graham 2480816 Nov  7 02:14 libsimpleble.so.0.6.0
-rw-r--r-- 1 graham graham 1042268 Nov  7 17:51 shared_libs.zip
-rwxrwxr-x 1 graham graham  924272 Nov  7 04:41 SimpleBleScanExample
graham@graham-dell:~/Pascal/SimpleBLE$ ./SimpleBleScanExample
./SimpleBleScanExample: error while loading shared libraries: libsimpleble.so.0: cannot open shared object file: No such file or directory
graham@graham-dell:~/Pascal/SimpleBLE$ 
```
I tried setting the LD_LIBRARY_PATH but that didn't help. Is there a "sudo apt get" command for installing the libraries?

Thanks!

**Comment by Gnome16** [comment]
OK, I've learned a lot more about RPATH than I wanted to, but I've found the problem:

```
<snip>$ readelf -d libsimpleble-c.so

Dynamic section at offset 0x1dd78 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libsimpleble.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libsimpleble-c.so.0]
 0x000000000000001d (RUNPATH)            Library runpath: [/home/erik/gitlocal/SimpleBLE/build/lib]
etc..

<snip>$ sudo apt install patchelf
<snip>$ sudo apt install chrpath
<snip>$ patchelf --set-rpath '$ORIGIN' libsimpleble-c.so
<snip>$ patchelf --set-rpath '$ORIGIN' SimpleBleScanExample
<snip>$ chrpath libsimpleble-c.so
libsimpleble-c.so: RUNPATH=$ORIGIN
<snip>$ ./SimpleBleScanExample
Found BLE adapter and got handle.
Adapter hci0 started scanning.
etc....
```

**Comment by eriklins** [comment]
Hello,
thanks for raising this issue. So, the runpath was getting compiled into the example as absolute path, correct? I wasn't aware of that, honestly. I cross-compiled the example for Linux with Lazarus on Windows. I will look into that whether it's possible to change this behavior in the Lazarus project.
Thanks.

**Comment by Gnome16** [comment]
There seem to be two issues.

The ScanExample program you provide runs, but when I recompiled it, it stopped working. I found this is because the build mode for 'Debug' has the linker command "-R ./" but I used the 'Linux64' build and that doesn't have it. Adding the command fixed that problem. An alternative is to use "-R $ORIGIN" which seems to work too. So you might want to update the projects in your download.

The other is that the library file libsimpleble-c.so.0 in the download has the RUNPATH hard coded to your /home/erik folder. This must be set somewhere by the CMAKE commands, but I'm not familiar with that so can't help you fix it. An easier fix would be to keep the existing builds but just run patchelf on that file for the download. Interestingly the file that needs patching is the libsimpleble-c.so one while the error provided by the program refers to the libsimpleble.so file. I don't know enough about Linux to understand what's going on there, but I suppose it's something to do with one library loading the other.

PS. I have tried contacting you by email using your Lazarus Forum details.

**Comment by eriklins** [comment]
I assume this has already been fixed in the SimpleBLE library and the build scripts. I udpated the bindings to today's main branch and recompiled and found that runpath is now set to "-R ./". I recompiled everything and pushed it here and also uploaded a new release package. Please let me know if this solves the issue.

**Comment by Gnome16** [comment]
I think this is OK now so can be closed. Thanks!
