### ISSUE TITLE
Allow dynamic loading in Windows

### ISSUE THREAD

**Issue by Gnome16** [eriklins/Pascal-Bindings-For-SimpleBLE-Library#13]
By just providing the references to the functions and labelling them 'external' the DLL files will be loaded statically. If there is a problem (e.g. the DLL file isn't found) then the program will throw a system error and fail to run.

Windows allows DLL files to be loaded dynamically using the LoadLibrary function. Now if the program fails to load the DLL files it is up to the program how to handle the error, perhaps by providing a message to the user.

This amendment adds the ability to load the libraries in Windows dynamically.

**Usage:**

By default static loading is still used. To use dynamic loading uncomment the line:
`{$DEFINE DYNAMIC_LOADING}`

There are then two functions exposed:
```
function SimpleBleLoadLibrary(dllPath:string=''): Boolean;
procedure SimpleBleUnloadLibrary();
```

In your program you can call the load routine without a parameter in which case Windows will search its normal path for the DLLs (e.g. in the EXE's directory and in Windows\System32). Or you can specify the path either as an explicit full path or a relative path. For example your code might be:
```
if not SimpleBleLoadLibrary() then begin
   if not SimpleBleLoadLibrary('./dll64') then begin
      writeln('Failed to load library');
      readln;
      exit;
   end;
end;
```
Before leaving your program you should clean up the memory by calling the SimpleBleUnloadLibrary procedure.

Note that one difference between the static and dynamic loading is that with static this would be allowed:
`if not SimpleBleAdapterIsBluetoothEnabled then writeln('BLE is not enabled on this PC');`
But with dynamic, even though the function has no parameters, it must still be called with the brackets:
`if not SimpleBleAdapterIsBluetoothEnabled() then writeln('BLE is not enabled on this PC');`

P.S. I would have added this as a pull request but I don't use Github much so didn't want to start creating forks etc!

[simpleble.zip](https://github.com/eriklins/Pascal-Bindings-For-SimpleBLE-Library/files/10562904/simpleble.zip)

**Comment by eriklins** [comment]
Fixed with commit [c63573eeabf750299cefe0a59d6161c54e92a95e](https://github.com/eriklins/Pascal-Bindings-For-SimpleBLE-Library/commit/c63573eeabf750299cefe0a59d6161c54e92a95e). Thanks @Gnome16.
