### ISSUE TITLE
SimpleBLE 0.8.2 and Lazarus 3.6.0 / FPC 3.2.2: Compile OK, crash in starting

### ISSUE THREAD

**Issue by FUCKTHECHRIST** [eriklins/Pascal-Bindings-For-SimpleBLE-Library#19]
I develop a project with SimpleBLE

Environments:
=============
Using Lazarus 2.2.0, FPC 3.2.2, SimpleBLE 0.6.0:
Compile OK
Running OK

Using Lazarus 3.6.0, FPC 3.2.2, SimpleBLE 0.8.2:
Compile OK
Running: Crash on starting (Invalid pointer)

**Comment by eriklins** [comment]
There were quite some API changes introduced with the recent version of SimpleBLE, which haven’t been ingested into the Pascal bindings.

Since I wasn’t able to get the bindings running with my InsideBlue app on Win11 anyway, I have currently no plans to work on this, I‘m afraid.

**Comment by FUCKTHECHRIST** [comment]
Using Lazarus **2**.2.0, FPC 3.2.2, SimpleBLE 0.6.0:
Compile OK
Running OK

Using Lazarus **3*.6.0, FPC 3.2.2, SimpleBLE 0.6.0:
Compile  NOT OK


Using Lazarus **3*.6.0, FPC 3.2.2, SimpleBLE 0.6.2:
Compile OK
Running: Crash
